services:
  qemu-gui:
    build: .
    restart: always
    privileged: true
    ports:
      - "443:5000"
      - "5800-5999:5800-5999"
    volumes:
      - C:\Certbot:/etc/letsencrypt
      - vms:/usr/src/app/vms
      - disks:/usr/src/app/disks
volumes:
  vms: {}
  disks: {}
